### ISSUE TITLE
@computed directive

### ISSUE THREAD

**Issue by AleF83** [Soluto/stitch#87]
Inspired from [here](https://github.com/graphql-community/graphql-directive-computed-property)

```js
type User {
    firstName: String
    lastName: String
    fullName: String @computed(value: "$firstName $lastName")
  }
```

**Comment by Mordech** [comment]
@yoavkarako Hey check this out. 👀

**Comment by tomeresk** [comment]
@Mordech @yoavkarako This is actually already implemented with the [localResolver directive](https://github.com/Soluto/stitch/blob/master/docs/directives/local-resolver.md), I'm gonna close the issue
